/** Isolated imperative hosts; remove each driver with its Svelte replacement. */
export interface LegacyHosts {
  readonly legacyMenu: HTMLElement;
  readonly legacyPlay: HTMLElement;
  readonly legacyOverlay: HTMLElement;
}
const MENU =
  '<section id="debug-identity" class="debug-identity" hidden="">\n            <div>\n              <label class="debug-id-label" for="debug-player-id">\n                Player ID\n              </label>\n              <div class="debug-id-row">\n                <input id="debug-player-id" class="debug-id-input" type="text" readonly="" spellcheck="false" autocomplete="off" placeholder="Available after Enter Game" aria-describedby="debug-player-id-hint">\n                <button id="copy-debug-player-id" type="button" class="debug-copy" data-copy-name="player ID" aria-label="Copy player ID" disabled="">\n                  Copy\n                </button>\n              </div>\n              <p id="debug-player-id-hint" class="debug-id-hint">\n                Gameplay log ID\n              </p>\n            </div>\n            <div>\n              <label class="debug-id-label" for="debug-session-id">\n                Page session\n              </label>\n              <div class="debug-id-row">\n                <input id="debug-session-id" class="debug-id-input" type="text" readonly="" spellcheck="false" autocomplete="off" aria-describedby="debug-session-id-hint">\n                <button id="copy-debug-session-id" type="button" class="debug-copy" data-copy-name="page session" aria-label="Copy page session">\n                  Copy\n                </button>\n              </div>\n              <p id="debug-session-id-hint" class="debug-id-hint">\n                Client log session\n              </p>\n            </div>\n          </section>';
const PLAY =
  '<div id="debug-play-stack" class="debug-play-stack">\n          <dl class="debug-play-identity">\n            <div>\n              <dt>Player</dt>\n              <dd id="debug-hud-player-id">—</dd>\n            </div>\n            <div>\n              <dt>Page</dt>\n              <dd id="debug-hud-session-id">—</dd>\n            </div>\n          </dl>\n          <button id="debug-hud-toggle" type="button" class="debug-copy debug-hud-toggle" aria-controls="debug-hud" aria-expanded="true" hidden="">\n            Hide HUD\n          </button>\n          <fieldset id="debug-hud" class="debug-hud" hidden="">\n            <legend>Debug health</legend>\n            <dl>\n              <div class="debug-hud-row">\n                <dt>FPS</dt>\n                <dd id="debug-hud-fps">—</dd>\n              </div>\n              <div class="debug-hud-row">\n                <dt>RTT</dt>\n                <dd id="debug-hud-rtt">—</dd>\n              </div>\n              <div class="debug-hud-row">\n                <dt>SNAP</dt>\n                <dd id="debug-hud-snap">—</dd>\n              </div>\n              <div class="debug-hud-row">\n                <dt>MOVE</dt>\n                <dd id="debug-hud-move">—</dd>\n              </div>\n              <div class="debug-hud-row">\n                <dt>WORLD</dt>\n                <dd id="debug-hud-world">—</dd>\n              </div>\n              <div class="debug-hud-row">\n                <dt>REL</dt>\n                <dd id="debug-hud-rel">—</dd>\n              </div>\n            </dl>\n            <button id="copy-debug-diagnostics" type="button" class="debug-copy debug-diagnostics-copy" data-copy-name="diagnostics" data-copy-label="Copy diagnostics" aria-label="Copy diagnostics">\n              Copy diagnostics\n            </button>\n          </fieldset>\n        </div>\n<button id="universe-map-toggle" type="button" class="universe-map-toggle" aria-label="Open universe map (M)" aria-keyshortcuts="M">\n          Map <kbd>M</kbd>\n        </button>\n<div id="touch-controls" class="touch-controls" hidden="" aria-hidden="true">\n          <button id="touch-contour-lock" type="button" class="touch-contour-lock" aria-label="Contour Lock" aria-pressed="false">\n            CONTOUR LOCK\n          </button>\n          <button id="touch-ability" type="button" class="touch-ability" aria-label="Ability" aria-disabled="true">\n            E\n          </button>\n        </div>\n<div id="spawn-fly-in-host"></div>';
const OVERLAY =
  '<dialog id="universe-map-dialog" class="universe-map-dialog" aria-labelledby="universe-map-title">\n      <header class="universe-map-header">\n        <div>\n          <p class="universe-map-eyebrow">Shared field cartography</p>\n          <h2 id="universe-map-title">Universe map</h2>\n          <p class="universe-map-subtitle">\n            Your nearby discoveries. Zoom out to explore the whole world.\n          </p>\n        </div>\n        <div class="universe-map-actions">\n          <button id="universe-map-close" type="button" aria-label="Close">\n            Close <kbd>Esc</kbd>\n          </button>\n        </div>\n      </header>\n      <div class="universe-map-stage">\n        <canvas id="universe-map-canvas" tabindex="0" role="img" aria-label="Shared universe map" aria-details="universe-map-locations"></canvas>\n        <ul id="universe-map-locations" class="universe-map-accessible" aria-label="Revealed landmarks and crew coordinates"></ul>\n        <div class="universe-map-compass" aria-hidden="true">\n          <span>N</span>\n          <i></i>\n        </div>\n        <button id="universe-map-center" type="button" class="universe-map-locate" aria-label="Center on you" title="Center on you" aria-keyshortcuts="Home" aria-pressed="true">\n          <svg class="universe-map-locate-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">\n            <title>Center on you</title>\n            <circle class="universe-map-locate-dot" cx="12" cy="12" r="3"></circle>\n            <circle class="universe-map-locate-ring" cx="12" cy="12" r="7"></circle>\n            <path class="universe-map-locate-cross" d="M12 2.5v3.2M12 18.3v3.2M2.5 12h3.2M18.3 12h3.2"></path>\n          </svg>\n        </button>\n        <div class="universe-map-legend"></div>\n      </div>\n    </dialog>';
export function mountLegacyHosts(hosts: LegacyHosts): () => void {
  const entries = [
    [hosts.legacyMenu, MENU],
    [hosts.legacyPlay, PLAY],
    [hosts.legacyOverlay, OVERLAY],
  ] as const;
  for (const [host] of entries) {
    if (host.childNodes.length !== 0) {
      throw new Error('Legacy host must have one owner.');
    }
  }
  for (const [host, markup] of entries) {
    host.innerHTML = markup;
  }
  return () => {
    for (const [host] of entries) {
      host.replaceChildren();
    }
  };
}
