import { DAMAGE, GAME } from '../src/constants';

/**
 * Shared spider tuning. Distances are world units and speeds are world units
 * per authoritative 60 Hz frame, matching server asteroid motion and the
 * client's GAME.MOTION_SCALE.
 */
export const SPIDER = {
  MAX_ACTIVE: 48,
  SILK_BURSTS: 4,
  SHUDDER_FRAMES: 30,
  CONSUMED_HISTORY_FRAMES: 180,
  MAX_ROAMERS: 1,
  NEST_SPACING: 10_000,
  NEST_SITE_RADIUS: 1_200,
  NEST_WAKE_DISTANCE: 4_200,
  NEST_SPAWN_SAFE_RADIUS: 1_600,
  NEST_PATROL_RADIUS: 240,
  NEST_ACQUIRE_DISTANCE: 420,
  NEST_LEASH_DISTANCE: 850,
  NEST_CHASE_FRAMES: 8 * GAME.FPS,
  NEST_GUARDS: [2, 4, 7],
  INFLUENCE_RADIUS: 280,
  SCUTTLE_SPEED: 1.25 * GAME.MOTION_SCALE,
  HUNT_SPEED: 4 * GAME.MOTION_SCALE,
  TURN_RATE: 0.04,
  HUNT_ACQUIRE_DISTANCE: 900,
  HUNT_RELEASE_DISTANCE: 2_600,
  MAX_HEALTH: DAMAGE.LASER_HIT * 3,
  BITE_DISTANCE: 44,
  HIT_RADIUS: 36,
  BITE_COOLDOWN_FRAMES: 60,
  SPAWN_INTERVAL_FRAMES: 3 * 60 * GAME.FPS,
  SPAWN_INTERVAL_MAX_FRAMES: 5 * 60 * GAME.FPS,
  SPAWN_RADIUS_MIN: 1_600,
  SPAWN_RADIUS_MAX: 2_200,
  FURNACE_SAFE_RADIUS: 360,
  STARTER_SAFE_RADIUS: 720,
  WORLD_INSET: 500,
  DESPAWN_DISTANCE: 5_600,
} as const;
